scripts/album.js
scripts/lychee_locale.js
scripts/photo.js
scripts/sidebar.js
scripts/view.js
styles/_content.scss

UI updated to display licenses for albums.
- New sidebar section for the visible album showing the current license
- `setLicense()` method added for albums from the sidebar
- Sidebar updates with new license stored in the table on load.

Album-level licenses

---

scripts/build.js

Also fix the incorrect pixel density.
There were several problems here.
The major one was that even though lychee.retinize() was being correctly invoked in build.album(), the result was not being passed to build.getThumbnailHtml().
A minor one was that lychee.retinize() was only invoked for the front picture and not for the two rotated ones behind it. Being a perfectionist I fixed that as well.
Finally, the "srcset" attribute in build.getThumbnailHtml() specified wrong pixel density. Since the "@2x" thumbnails are 400x400 vs 200x200 for the regular ones, that value should obviously be "2x" but for some reason "1.5x" was being used.

Use HiDPI thumbnails in albums overview

---

scripts/build.js
scripts/lychee.js
scripts/lychee_locale.js
scripts/settings.js
scripts/view.js
styles/_justified_layout.scss
styles/_settings.scss

Here's my initial attempt at implementing unjustified layout as described in https://github.com/LycheeOrg/Lychee/issues/199.
In the end I didn't need to use any third-party packages. I just needed to set the dimensions of each `<div photo>` (I originally thought that they could inherit them from the `<img>` tags inside but I guess that's not how it works). With the correct dimensions, the browser takes care of the rest.
I didn't want to hard-code the height of individual images so instead it's set in the CSS so a user should be able to override it. I set it to 240px, which looks good to me (Google Photos has it at 220px by default, I think). Another way to do it would be to tie it to the height of small images, I guess...
I tried to keep the original code as-is as much as possible. In …

Unjustified layout

---

scripts/main/contextMenu.js
scripts/main/lychee_locale.js
scripts/main/photo.js

See https://github.com/LycheeOrg/Lychee-front/pull/36
Extend frontend to correspond to [LycheeOrg/Lychee#216](https://github.com/LycheeOrg/Lychee/pull/216), implements [LycheeOrg/Lychee#204](https://github.com/LycheeOrg/Lychee/issues/204)
This adds 2 additional entries in the context menu of a photo. The entries only show up if medium and/or small sizes are available.

allow download of small & medium files

---

scripts/main/albums.js
scripts/main/build.js
scripts/main/init.js
scripts/main/photo.js
scripts/main/view.js

This merge request addresses https://github.com/LycheeOrg/Lychee/issues/198.  See https://github.com/LycheeOrg/Lychee-Laravel/pull/92 for the server part and the overview/motivation of why things are done the way they are.
As implement, support for HiDPI requires extensions to the server API. However, I kept the extensions optional so the new frontend can be used with Lychee v3 without any loss in existing functionality (I only implemented the server changes for the v4).
I thought I would discuss some parts of the patch:
I got rid of `build.getThumbnailHtml()` because extending it to handle HiDPI small/medium would require something like 8 new arguments.  So I replaced it with a much simpler `build.getAlbumThumb()` that's used just for the square thumbnails in albums view, and the rest of …

Frontent part of full HiDPI support

---

styles/main/_justified_layout.scss

Fixes https://github.com/LycheeOrg/Lychee-Laravel/issues/109.
Basically, the justified and unjustified layout inherited `width: 180` from the square layout. This patch resets the width and sets the right margin to be the same as the left one.

Remove the width restriction from overlay title

---

scripts/main/view.js

Fixes https://github.com/LycheeOrg/Lychee-Laravel/issues/101.
Basically, on hitting Reload, all the views seem to restart, including the album view "behind" the photo view. Only there is no real album view at that point, so the container width is 0 and all the layout calculations end up being wrong.
Perhaps somebody better versed in JavaScript can come up with a better fix. What I did was add a custom fallback code that does its own calculation of the container width based on the window width.

Fix album view on reload in photo view

---

scripts/main/build.js

This is a minor fix to the fallback retinize code for Lychee v3 to ensure that we do not add the `srcset` tag for svg images. It didn't do any harm but it was untidy.

Don't retinize svg images

---

scripts/main/password.js

Viewing a password-protected album can be annoying because every time you leave the album and want to re-enter it, you are asked for the password again. This is especially bad if that album has subalbums; the password needs to be reentered when going back from each subalbum to the parent album.
This can be easily prevented by caching the passwords in memory, inside the album object.

Cache album passwords in memory

---

scripts/main/header.js
scripts/main/init.js
scripts/main/lychee.js
scripts/main/lychee_locale.js

Finally takes care of my pet project https://github.com/LycheeOrg/Lychee-Laravel/issues/94
There are also corresponding changes to the server(s). Since they are trivial, I implemented them both for v3 and v4.
I added two new buttons to album and photo views (Enter and Exit Fullscreen), only one of which is shown at any one time. I figured it was easier to do it that way than to change the button at run time.
I was wondering whether to also add the buttons to the public (and albums) views, but I thought it might be excessive, especially in the public view case where there aren't any buttons now. Let me know if you think I should add them though.
I also added the 'F' keyboard binding, as requested by @ildyria. While I was there, I fixed the 'o' keyboard binding, which was misbehaving on …

Add fullscreen support to album and photo views

---

scripts/main/lychee.js

@ildyria I thought you wanted it bound to `F`? :smiley:
Anyway, lowercase `f` didn't work in public mode because we explicitly unbind it. This patch fixes it.

Don't unbind 'f' in public mode anymore

---

scripts/main/album.js
scripts/main/albums.js
scripts/main/password.js

Front-end-side fixes for https://github.com/LycheeOrg/Lychee-Laravel/issues/139
The change to `album.js` makes `albums.getByID()` search recursively through subalbums. It's kind-of amazing how everything else worked fine without it :smiley: 
The change to `password.js` removes a shortcut that appears to be bogus? I'm not sure why the code used to check the password-protection status of the parent album when determining whether to ask for the password of a subalbum. As a result, if the parent album was not password-protected, it would never ask for the password for the subalbum, so a password-protected subalbum could not be opened.

Subalbums passwords

---

styles/main/_justified_layout.scss

One more tweak to the unjustified layout. Because of `overflow: hidden` (needed to avoid the horizontal scrollbar for very narrow windows), image selection outline was missing on the outside edges of the viewport. I moved the margins around to ensure that every image has space for the outline.

Tweak layout so that selected outline is shown

---

scripts/view/main.js

We need to set `sizes` to indicate maximum expected image width. We already do it for the regular photo view and for the frame view; this just completes support for standalone photo view.

Add missing support pieces for srcset

---

scripts/main/contextMenu.js

Implement one of @jprokop1's suggestions from https://github.com/LycheeOrg/Lychee-Laravel/issues/102: add Root album to the list of albums one can switch to.

Add Root to the album title pop-down menu

---

scripts/main/header.js

If `full_photo` is disabled in the settings and the album is not downloadable, there's no point in displaying the More button in photo view in the public mode, since the menu will be empty.

Hide More button in photo view if menu is empty

---

scripts/main/album.js
scripts/main/contextMenu.js
scripts/main/photo.js
scripts/main/view.js

There's a bunch of related fixes here. Most of them are v4-specific, but not all.
The bulk of the changes is in `album.js` and `view.js`. They fix #62 and the related problem when deleting sub-albums. They also fix #68. Basically, support for sub-albums was incomplete so the UI was acting in unexpected and confusing ways (although the right thing was happening on the server side). I effectively added sub-album-specific equivalents of methods that already existed for photos.
One oddity I found in `album.js` was a duplicate definition of `album.getParent()`. I deleted one of them.
The change to `contextMenu.move` is a minor fix to ghost out the parent album of the currently displayed photo in the menu where one can select a destination album for a move operation.
Changes to `photo.js` fix …

Fix rename move delete

---

package.json
scripts/main/contextMenu.js
scripts/main/header.js
scripts/main/lychee.js

Fix https://github.com/LycheeOrg/Lychee-Laravel/issues/227: allow merging with the parent album.
Display albums and shared albums in the pull-down navigation bar even if only one is present (in v3 if only one was present then it was guaranteed to be us but in v4 that's not the case).
Allow moving/merging with shared albums if admin (admin should be able to do everything, right?).
Add 'Move Album' button to album view (we had one in photo view so it was conspicuously missing here).

Assorted, v4-specific move/merge fixes

---

scripts/main/sidebar.js

This is the easy part: the count of subalbums in the current album. No recursive counting (yet).
Only display image count if non-zero.
Don't display resolution for videos if metadata is missing.
Server side is in https://github.com/LycheeOrg/Lychee-Laravel/pull/231.

Add count of subalbums

---

scripts/main/albums.js
scripts/main/contextMenu.js

Always show Merge in album's context menu.
Also exclude current album's parent from move destinations.
Note: server side changes are in https://github.com/LycheeOrg/Lychee-Laravel/pull/232.

Add support for tree structure of albums

---

scripts/main/album.js
scripts/main/build.js
scripts/main/contextMenu.js
scripts/main/header.js
scripts/main/init.js
scripts/main/lychee.js
scripts/main/multiselect.js
scripts/main/sidebar.js
scripts/main/view.js

Work in progress. It works for me but needs a little more testing (in particular, I still need to test if I didn't break anything with v3). Some input wouldn't hurt either :smiley:.
The primary functionality is the disabling of editing capabilities in shared albums for regular users. Given that we can trigger edits using header buttons, context menu, and keyboard bindings, it's a lot of code to tweak... Once this is merged, https://github.com/LycheeOrg/Lychee-Laravel/issues/219 can be closed... Also, this part depends on https://github.com/LycheeOrg/Lychee-Laravel/pull/260.
As I was implementing this, I got distracted by something that was on my todo list for a while: enabling the pull-down album/photo list in `publicMode`. Until now it was only available for logged in users, for no good …

Prevent attempts to edit shared albums by others

---

scripts/main/header.js
scripts/main/view.js

Disable the pull-down menu in albums view since it conflicts with the use of the same space as a link to the landing page.
Don't assume that the landing page is at the top-level URL.

Undo albums menu

---

gulpfile.js
package.json
scripts/main/view.js

Body scroll locking on iOS Safari not working with simple css "overflow: hidden". Vertical swipe movements on iOS cause scrolling of thumbnails in background and visual artifacts for lightbox.
NPM package "body-scroll-lock" provides a simple solution to fix this issue.
See some more details: https://medium.com/jsdownunder/locking-body-scroll-for-all-devices-22def9615177

Fix body scroll locking on iOS for Lightbox

---

styles/main/_logs_diagnostics.scss
styles/main/_sidebar.scss
styles/main/main.scss

Fixes #23.
In the end I opted for a conservative approach of keeping the global disabling of selection (somebody did it for a reason...) so I only enabled it for the texts in the sidebar. Seems to work fine with firefox and chrome.

Sidebar select

---

scripts/main/leftMenu.js
scripts/main/multiselect.js
scripts/main/view.js
styles/main/_content.scss
styles/main/_multiselect.scss
styles/main/_sidebar.scss

Fixes #75, #84, and more.
Rational support for "Select all" in albums with photos and subalbums
(do not generate an error message).
Add support for Shift key to select a range of albums or photos.
Intuitive clearing of selection with a single click.
multiselect.removeItem() didn't work correctly for non-first items.
Selection couldn't start much below the last picture in albums with just
a few pictures (i.e., those that had whitespace there).
Cleaned up calculations of selection and overlap.
New multiselect.unbind() function to match the existing
multiselect.bind().

Assorted multiselect fixes

---

scripts/main/header.js
scripts/main/lychee.js
scripts/main/photo.js
scripts/main/view.js
styles/main/_imageview.scss

This branch used to contain more changes but I pulled some of them into `download-improvements`.
What remains is the commenting out of the debug output and preventing the next/prev arrow wrappers from overlapping the video playback. The latter is necessary because the video playback widget typically contains buttons such as start/stop, and they end up being impossible to click on because the arrow wrappers cover them. It's very confusing when one tries to click on Pause and instead a previous image is loaded...
As I wrote in the comment, the result is imperfect (now the video playback tends to cover part of the background image behind the prev/next arrows) but I can't think of an easy way to make it better.

Assorted fixes

---

scripts/main/build.js
scripts/main/photo.js
scripts/main/view.js
styles/main/_imageview.scss

Fixes #129.
The display of the thumbnail in the photo view while the larger-resolution image is being loaded is implemented using CSS background image (on the `<img>` object, no less). It actually looks pretty cool, I think.
Image prefetching code was extended to request both previous and next images. The prefetch request is initiated only after the main image has finished loading. We no longer prefetch movie files. There's now a fallback for browsers that don't support HTML5 `link rel=prefetch`. While the fallback was trivial, detecting whether it's needed was not. I thought I would be forced to hardcode it based on the user agent, but in the end I found some code that's supposed to detect it at run time.
Code was also extended in places to handle the case of previous or next image being …

Nextprev improvements

---

scripts/main/view.js

While working on the memory leak in Import, I noticed that Firefox was very slow in unjustified layout for large albums. I still don't understand exactly why it was slow, but this PR fixes it.

Speed up unjustified layout in Firefox

---

.gitignore

MacOS creates .DS_Store files, which contain custom attributues of the folder. These files need to be ignored by git.

Add .DS_Store to gitignore list

---

scripts/main/build.js
scripts/main/lychee.js
scripts/main/photo.js
scripts/main/sidebar.js
scripts/main/view.js
styles/main/_sidebar.scss

Do not autoplay videos accessed via the previous or next button (or swipe left/right). There's no way for the user to tell ahead of time that they are video file so autoplay may be undesirable.
Also clean up the new map display:
* limit the precision of altitude and direction to something sensible
* display direction only if present
* use https to access the OSM data
* move style to the style file
* make the front end default match the server default
* indentation fixes

Selective autoplay

---

scripts/main/contextMenu.js
scripts/main/photo.js

Fixes https://github.com/LycheeOrg/Lychee-Laravel/issues/362.
Fixes #151.
* Disable New Album when moving the current album
* Fold the redundant Duplicate feature into Copy to...
* Use the new albumID argument to Photo::duplicate so that the duplicate rather than the original moves (depends on https://github.com/LycheeOrg/Lychee-Laravel/pull/364)

Various fixes

---

scripts/main/header.js
scripts/main/lychee.js
scripts/main/view.js

Hi,
I saw that several translations do not work, so I added this change to be displayed.
But I do not apply all the translations because multiple words like "More", "Full configuration", "Search" among others that do not exist in "php / Locale / English.php" and I would like to add them but I don't know if I also have to add them to "Lychee-front / scripts / main / lychee_locale.js"? and I also don't know if there would be a problem with this new translation in the other languages? (Italian.php, German.php, etc).
Could you help me with these questions before changing anything.
Thank you.

Added function to apply translations to the header

---

.gitignore
scripts/main/init.js

This PR adds support for uploading images by pasting them from clipboard into Lychee.
Tested in Chrome 77 and Firefox 69 on Windows 10.
**Important:** This does not add support for uploading images by pasting an **URL** from clipboard, as requested in the Feature Request.
That's because I found it unnecessary to have this feature when you could just use the normal "+" -\> "Import from Link" method
**Also Important:** On Windows 10, I've tried to copy an image file in Explorer and paste it into Lychee. This didn't work for some reason. But what definitely works is going to a random website, clicking on an image, clicking "Copy Image" and then pasting it into Lychee!
1. Go on a random website with images (for example [unsplash.com](https://unsplash.com))
2. Click on an image you want to …

Added basic support for uploading images by pasting from clipboard

---

scripts/main/sidebar.js
scripts/main/view.js

Another overdue patch. Cleans up and fixes missing cases in the updating of subalbum/image/video counts in the sidebar after delete operations. In the process gets rid of a completely unnecessary `album.json.num` so that in the future we can remove it from the server as well (it's only needed for smart albums).

Correct the updates of the counts in the sidebar

---

scripts/main/init.js

This is an overdue patch to clean up when we allow drag-and-drop or image paste operations. In my opinion, they should be supported only in albums or album views, when there are no dialog windows/menus/etc. being displayed. Otherwise there's a good chance that the operation was performed accidentally.

Support drag-and-drop or paste in well-defined UI state only

---

scripts/main/view.js

In case of videos without ffmpeg installed, there are not thumbs.
Thumbs are used to left/right arrows in the lightbox. We use the fallback play-icon in this case.

Fix issue of left/right arrows in case of no thumb

---

scripts/main/init.js
scripts/main/swipe.js

Fix toggling of header in 2 cases
1. single touch does not toggle header (#174)
Event 'mousemove' gets called after a single touch and 'mousemove' makes header appear; Solution is to prevent event 'mousemove' to be called after 'touchend'
2. swipe forward / backward toogles header
Swiping forward / backward triggers 'touchend' event, which toggles the header. Solution is to prevent toggling if 'swipeend' triggered loading of previous/next photo

Fix toggle of header

---

.travis.yml
gulpfile.js
package.json
scripts/main/album.js
scripts/main/albums.js
scripts/main/build.js
scripts/main/header.js
scripts/main/init.js
scripts/main/leftMenu.js
scripts/main/lychee.js
scripts/main/mapview.js
scripts/main/photo.js
scripts/main/tabindex.js
scripts/main/view.js
styles/devices/TV.scss
styles/main/_content.scss

This PR adds basic support to view Lychee on a FireTV as a WebApp.
In a nutshell:
* Navigation is done using the 'tabindex' property of elements
* We need to enable/disable this features as element can be focused even if they are not visible 
* Several navigation elements are disabled since they are not needed on a TV
* Device specific CSS (using white to highlight nav elements) used
* FireTV doesn't like transparency and several layers of elements on top of each other (performance) 
* UI for Desktop and mobile remains unchanged

Support fire tv

---

scripts/main/build.js

This fixes a regression I've noticed where we no longer print the take date of photos underneath their names in the album view. This is because the server no longer sends the `cameraDate` field. We can rely on the `takedate` instead though.

Don't rely on cameraDate

---

scripts/main/header.js
scripts/main/tabindex.js

Fixes a bug introduced in #205.
The bug manifested itself as the search input field becoming permanently disabled after one switches to album view and then back to albums/public view.
The issue was that `tabindex.makeFocusable` is a noop if tabindex is not enabled, but an identical test was missing from `tabindex.makeUnfocusable`. Same with saveSettings/restoreSettings although I don't know if that could cause any real problems.
While looking for the bug I also spotted a copy-paste error that I fixed.

Fix unfocusable

---

scripts/main/init.js

Restores some of the enter actions that were inadvertently disabled in #205.
In particular, restores enter in all basic modals, not just in the signin one. I did keep @tmp-hallenser's change of only applying it to modals with active input fields though. So the second enter in the advanced settings still won't work but that doesn't bother me.
The event is also bubbled up if nothing was clicked which restores the first enter in the advanced settings.
I also cleaned up the indentation while I was there :smiley:.

Restore enter actions in more input fields

---

scripts/main/album.js

Fix: https://github.com/LycheeOrg/Lychee/issues/658
Set parent album to `0` when creating a new album in SmartAlbum.
I referred to the below comment.
>  https://github.com/LycheeOrg/Lychee/issues/658#issuecomment-657112143
---
Thank you :)

fix: 422 error when create new album in SmartAlbum

---

.travis.yml
README.md
package.json

Currently nodejs supports higher than `v10.x`
> [Release schedule](https://github.com/nodejs/Release/tree/23a3ffd4d289ad8d5e7c1b14f2a004a1cad78292)
* Update README.md
* Add `engines` option in `package.json`
* Set nodejs cross-build on travis ci
---
Thank you :)

chore: require nodejs v10.0.0 or later and cross build on travis-ci

---

gulpfile.js
package.json

Use [`del`](https://www.npmjs.com/package/del) instead of [`gulp-rimraf`](https://www.npmjs.com/package/gulp-rimraf) when clean in the gulp task.
As `gulp-rimraf` owner favors of [gulp official delete file recipe](https://github.com/gulpjs/gulp/blob/1693a1127116a6804a892a4b931c232b1bec9162/docs/recipes/delete-files-folder.md).
> Deprecated in favor of https://github.com/gulpjs/gulp/blob/master/docs/recipes/delete-files-folder.md
And it is use [`del`](https://www.npmjs.com/package/del) package.
Thank you :)

chore(deps): use del instead of gulp-rimraf

---

package.json

Move some dependencies from `dependencies` to `devDependencies` in `package.json`
The `devDependencies` are just for development dependency that like gulp (task runner), babel (transpiler), etc...
It is similar to `require` and `require-dev` relationship in `composer.json` for PHP.
IMHO, it is better to separate them for developers.
Thank you :)

some dependencies move from dependencies to devDependencies

---

README.md

Looks like since the v4 the Lychee main repo doesn't include the docs a submodule, so no need to keep it in the install steps.

Update README to remove ref to obsolete submodule

---

scripts/main/album.js
scripts/main/photo.js
scripts/main/photoeditor.js
scripts/main/view.js

This fixes image rotation (https://github.com/LycheeOrg/Lychee/issues/741).
The main fixes are on the server side. The front end changes do the following:
* Work with the new server rotation API that returns a full updated photo object rather than just `true`.
* Correctly handle the "2x" cases.
* Handle updates to album thumbs.
* Hide the rotation buttons for unsupported photo types.
* Update metadata in the sidebar.
There's also an unrelated small fix to the photo delete confirmation dialog removing a spurious space.

Fix rotation

---

scripts/main/lychee.js
scripts/main/view.js

This is the frontend code addressing LycheeOrg/Lychee#886, reading the configuration object and not displaying the directional cone if the setting is off.

frontend code for disabling direction display on embedded map

---

scripts/main/build.js
scripts/main/lychee.js
scripts/main/photo.js
styles/main/_content.scss
styles/main/_imageview.scss

This pull request addresses a few minor issues with the front-end:
1. When sorting albums by anything but timestamps (e.g. by title), the date below the title shows the import date. Regardless of sorting preferences it seems preferable to display the date range of photos in the album (`build.album`, l.84-89).
2. Photo views show no overlay if EXIF info is missing. In these cases the overlay should at least show the title and the creation/upload date (`build.overlay_image`, l.253ff)
3. For media files with corrupt/incomplete EXIF information a few checks are performed while compiling the overlay to prevent empty fields (`build.overlay_image`, l.275ff)

Display takedate for photos and albums

---

scripts/main/lychee.js
scripts/main/upload.js

Implements a limit on the number of photos being simultaneously processed during upload.  I expected that adding this would complicate the `process` function but in fact it simplified it (since it was needlessly complicated to begin with).
This implements what was discussed in  https://github.com/LycheeOrg/Lychee/issues/903 and https://github.com/LycheeOrg/Lychee/issues/913. The default limit is `4`. Setting it to `0` disables the limit.
There will be a trivial corresponding server-side PR that adds a config variable.

Support upload_processing_limit

---

scripts/api.js

Something changed somewhere (Laravel? Lychee's recent refactoring?) and session timeouts now seem to generate a different response than before. Support this new response in addition to the old one (no idea if the old ones are still generated).

Fix the timeout handling

---

scripts/main/lychee.js
scripts/main/photo.js

This is just a minor front end companion to https://github.com/LycheeOrg/Lychee/pull/932. It doesn't add any new functionality; it just makes sure that the visibility dialog for photos correctly reflects the setting of the new `public_photos_hidden` config.

Show the state of public_photos_hidden

---

scripts/main/contextMenu.js
scripts/main/settings.js
scripts/main/view.js

* suppress 'import from dropbox' in context menu if no key is set
* do not throw error if dropbox key is cleared (set to empty)
* resolves #81

fix dropbox context menu entry (#81)

---

scripts/main/contextMenu.js
scripts/main/header.js
scripts/main/init.js
scripts/main/lychee.js
scripts/main/view.js
scripts/main/visible.js
styles/main/_basicModal.custom.scss
styles/main/_content.scss
styles/main/_header.scss
styles/main/_imageview.scss
styles/main/_justified_layout.scss
styles/main/_leftMenu.scss
styles/main/_logs_diagnostics.scss
styles/main/_settings.scss
styles/main/_sharing.scss
styles/main/_sidebar.scss
styles/main/_u2f.scss
styles/main/_users.scss

This PR is an attempt at improving support for small screens in general and phones in particular. This adds responsive web design features to adjust the size of albums and photo thumbnails based on size of screen. It also adjusts margins and title size as well as suppresses subtitles to improve visibility of small thumbnails.
As an aside, I have some further ideas for improving the user experience on touch devices (for example, toggling the overlay on images doesn't seem to work for touch). Let me know if changes in this direction are of interest.

add responsive web design for small screens

---

API.md
scripts/api.js
scripts/main/album.js
scripts/main/albums.js
scripts/main/build.js
scripts/main/contextMenu.js
scripts/main/header.js
scripts/main/leftMenu.js
scripts/main/lychee.js
scripts/main/photo.js
scripts/main/upload.js
scripts/main/view.js

That should have been done a while ago...

Remove all references to lychee.api_V2

---

scripts/main/album.js
scripts/main/lychee_locale.js
scripts/main/photo.js
scripts/main/sidebar.js

Changed frontend to use the JSON attribute `filesize` which reports the size of an photo in bytes. The filesize is converted to a localized string by the frontend.

Refactor to use raw filesize

---

scripts/main/album.js
scripts/main/albums.js
scripts/main/build.js
scripts/main/lychee_locale.js
scripts/main/mapview.js
scripts/main/photo.js
scripts/main/sidebar.js
scripts/main/view.js

This PR is a new attempt for the unfortunate, previous [PR #262](https://github.com/LycheeOrg/Lychee-front/pull/262).
Changes since the previous PR:
- The method `lychee.locale.printDateTime` has been changed such that date/time strings are printed in localized format by with respect to the original timezone of the photo.

Refactor timestamps anew

---

scripts/main/album.js
scripts/main/init.js
scripts/main/search.js
scripts/main/view.js

Fixes https://github.com/LycheeOrg/Lychee/issues/1027
This is essentially a cleanup of #230, which was restricted to albums with subalbums, as well as of some old code dating presumably to v3.
The bug in https://github.com/LycheeOrg/Lychee/issues/1027 was I believe due to a race condition between two callbacks with timeouts in `album.js`: one loading the content, the other restoring the scroll position. I solved that by moving the restoring code to `view.js` (where it gets invoked from the content loading callback).
In the process I noticed that there were two different versions of scroll position restoring code: one for the top level albums view (probably an old code dating back to v3), and another for albums with subalbums (from #230). We also didn't save the scroll position of albums …

Rework scroll position saving

---

scripts/main/photo.js

Fixes "Copy To..." functionality
This was broken in #257. Basically, the front end had two implementations of this functionality: one for v3 and one for v4. Erroneously, instead of removing the v3 implementation, it became the default. As a result, _Copy To_ would create a duplicate in the destination album _and_ move the source photo(s) to that album as well.

Remove erroneously left v3 code

---

scripts/main/view.js

This fixes #273.
Indeed we must use so-called template strings (see ECMAScript Spec) and double dollar signs `$$` to properly escape strings which come from `Lychee.locale` (or any other JS string). If we do not, it might happen that the inserted string interferes with the outer HTML if the string happens to include certain characters which have a special meaning in HTML, e.g. `<`, `>`, `'`, `"`, `!`, `&` and probably some more.
Looking around for `Lychee.locale` in the JS source code, I fear that there are probably many more places which are incorrect. Lucky us that we did not fall into this trap any earlier. However, this fix only repairs the bug at hand. I did not fix every potentially problematic spot.

Fixes #273.

---

scripts/main/header.js
scripts/main/init.js
scripts/main/lychee.js
scripts/main/search.js
scripts/main/sidebar.js
scripts/view/main.js

> Possible fix for https://github.com/LycheeOrg/Lychee/issues/653
This PR brings an enhancement to the front-end: remembering if the user wants to have the "about" panel open or not.
1.  Open an album or a photo
2. Click on the "info" button or press the `i` key
3. Go back to a view where the "about" panel can't be shown
4. Open an album or a photo
5. The "about" panel is always closed, regardless of its last user-set state
1.  Open an album or a photo
2. Click on the "info" button or press the `i` key
3. Go back to a view where the "about" panel can't be shown
4. Open an album or a photo
5. The "about" panel is closed or open, based on the last user choice
In this PR, a solution is proposed.
- We should distinguish whether or not toggling the "about" panel visibility is user-generated or …

Remember user preference for the visibility of the "about" panel

---

scripts/main/album.js
scripts/main/photo.js
scripts/main/sidebar.js

This PR goes with [this backend PR](https://github.com/LycheeOrg/Lychee/pull/1239) to adapt the migration of filesize from `Photo` to `SizeVariant`.

Use filesize in original size variant - see Lychee PR #1239

---

.gitignore
scripts/main/sidebar.js

The attributes `latitude` and `longitude` are nullable JS numbers. The latitude and longitude 0°0'0''.0000 are valid coordinates, but falsy in JS. So we must not use shortcut notations like `if (latitude)` to check if we have a latitude/longitude, but explicitly check for `!== null` .

Fix location type

---

package.json
scripts/main/album.js

During review of #291 I noticed that `album.buildMessage` does not work as expected, because the previous version only searches for the designated album ID in `albums.json.albums`, i.e. inside the root album. Hence, the confirmation message in #291 did not show the correct title of albums when used inside sub-albums.
I cannot remember to have changed this method during my re-factoring, but it seems so. Now it should be fixed.

Fix regression bug

---

scripts/main/album.js
scripts/main/albums.js
scripts/main/contextMenu.js
scripts/main/init.js
scripts/main/lychee_locale.js
scripts/main/view.js

Fixes https://github.com/LycheeOrg/Lychee/issues/1307
Also fixes uploads via keyboard (`u`) and the confirmation string displayed for tag albums (which incorrectly informed that the contents of a tag album would be deleted).
Also includes an unrelated fix to prevent the info sidebar from being displayed in settings and such (if it was being displayed for an album and somebody then moved to the albums view and opened the settings).

Fix tag albums

---

scripts/main/contextMenu.js
styles/main/_basicContext.custom.scss
styles/main/_basicContext.extended.scss

This PR fixes #309 by limiting the width of context menus and wrapping long menu entries. As a small aside it also assigns a fixed position to the add/more menu (upper right corner) rather than based on the click location (always below the menu bar rather than overlapping).

wrap long menu entries

---

scripts/main/header.js

Fixes #387 
This logic nesting is not very intuitive. I tried to untangle it and fix the "hide more menu" functionality.
It now works for my examples (public album with and without download enabled, hidden album with download enabled).

Fix more menu in photo view (#387)

---

gulpfile.js
package-lock.json
package.json

This adds the resize-observer-polyfill module to frontend.js, which allows the frontend to run on browsers that do not support ResizeObserver (like iOS 12).

Add ResizeObserver polyfill to frontend.js (#382)

---

scripts/main/header.js

Fixes #384
The "#button_share" element is being hidden before (`if (!lychee.share_button_visible)` block), however it is shown again in the "Hide buttons if needed" block. It should only be shown if `enable_button_share` and `share_button_visible` are truthy.

Hide share button on photos page when share_button_visible is false (#384)

---

scripts/main/upload.js

This PR is part of the https://github.com/LycheeOrg/Lychee/issues/1729 enhancement.
It modifies the front-end to also send the file's modified time to the back-end. The time is sent as a timestamp.

Send the file's last modified time to backend

---

scripts/main/lychee.js

Fixes https://github.com/LycheeOrg/Lychee/issues/1775
albumID is not urldecoded which results to a fail when checking against album.json.id === albumID. This is fixed here by urldecoding.

Fixes #1775 from LycheeOrg

---

scripts/main/build.js

Fixes GUI part of LycheeOrg/Lychee#2002.
If album_decoration==photo, show photo count only if at least one photo in album (same as for album_decoration==all).

Fix photo count of zero or undefined
