LycheeOrg/Lychee-front

- scripts/leftMenu.js
- scripts/loadingBar.js
- scripts/lychee.js
- scripts/settings.js
- scripts/view.js
- styles/_loading.scss
Settings are now grouped in a single page.
New locale have been created:
```php
'SUCCESS'			: 'OK',
'SETTINGS_SUCCESS_LOGIN'	: 'Login Info updated.',
'SETTINGS_SUCCESS_SORT'		: 'Sorting order updated.',
'SETTINGS_SUCCESS_DROPBOX'	: 'Dropbox Key updated.',
```
> Change layout of settings

- scripts/build.js
- scripts/view.js
- styles/_content.scss
See [https://github.com/LycheeOrg/Lychee/pull/74](https://github.com/LycheeOrg/Lychee/pull/74)
> Added video compatibility

- scripts/build.js
From issue [https://github.com/LycheeOrg/Lychee/issues/4#issuecomment-436333501](https://github.com/LycheeOrg/Lychee/issues/4#issuecomment-436333501)
> Added MOV as an accepted video format

- scripts/albums.js
- scripts/build.js
- styles/_content.scss
See https://github.com/LycheeOrg/Lychee/pull/77
> Added video thumbnail

- scripts/album.js
- scripts/contextMenu.js
when a new album is added this way.
Fixes LycheeOrg/Lychee#38
Rewrite of LycheeOrg/Lychee#84
> Show "Move All -> New Album" at all times. Actually move the photos

- scripts/csrf_protection.js
> Don't add X-XSRF-TOKEN headers to update checks.

- scripts/search.js
- scripts/view.js
> Fix typos from d404ef8 (PR #13).

- scripts/album.js
- scripts/albums.js
- scripts/build.js
- scripts/contextMenu.js
- scripts/header.js
- scripts/init.js
- scripts/lychee.js
- scripts/multiselect.js
- scripts/photo.js
- scripts/sidebar.js
- scripts/view.js
- styles/_content.scss
- styles/_users.scss
Add multiselection with CTRL key.
Add support for sub albums (for later... :) )
> Mutli select

- gulpfile.js
- package.json
- scripts/album.js
- scripts/build.js
- scripts/init.js
- scripts/lychee.js
- scripts/view.js
- styles/_content.scss
- styles/_justified_layout.scss
- styles/main.scss
requires a:
`npm install` to add https://www.npmjs.com/package/justified-layout
> justified layout completed

- styles/_content.scss
Fix for issue https://github.com/LycheeOrg/Lychee/issues/133
> Issue #133

- scripts/frame/main.js
Front end component of https://github.com/LycheeOrg/Lychee-Laravel/pull/118.
Server now returns the whole Photo object. I extract the data for the `srcset` attribute from it. I also added a resize callback to update the `sizes` attribute (the Photo object is stored as `frame.photo` so that the callback can access it; it only really needs it for the aspect ratio).
> Add HiDPI support to Frame mode

- scripts/main/album.js
- scripts/main/build.js
- scripts/main/lychee_locale.js
- scripts/main/settings.js
- scripts/main/view.js
- styles/main/_users.scss
Also add hover explanations for the icons/checkboxes.
Finally, tweak the layout so that columns align nicely.
> Hide passwords in users view

- scripts/main/build.js
Scope of the variables was too limited so the fallback code in thumb2x handling for v3 didn't work.
Also, there was some (harmless) code duplication.
> Fix v3 fallback code for thumb2x

- scripts/main/init.js
- scripts/main/multiselect.js
- scripts/main/search.js
Use user-selected photo layout when displaying photos in search results.
Also fix context menu for photos in search results.
Note than on v3 this depends on https://github.com/LycheeOrg/Lychee/pull/248.
> Fix search

- scripts/main/contextMenu.js
- scripts/main/multiselect.js
> Fix blue select

- scripts/main/leftMenu.js
- styles/main/_header.scss
- styles/main/_leftMenu.scss
Improve the usability of the left menu.
> Close text

- scripts/main/photo.js
- scripts/main/view.js
Follow-up fixes to #70; should hopefully fix #63 for good this time.
> Correctly handle delete/move from photo view

- gulpfile.js
> Add missing image file

- scripts/main/sharing.js
- scripts/main/users.js
- styles/main/_logs_diagnostics.scss
- styles/main/_settings.scss
- styles/main/_sharing.scss
- styles/main/_users.scss
Add additional sanity checks in Users and Sharing views to prevent server errors.
Improve the styling in the Users view (at least I think I improved it :smiley:).
> Fix album selection in sharing.delete

- gulpfile.js
- package.json
- scripts/main/header.js
- scripts/main/init.js
- scripts/main/lychee.js
- scripts/main/lychee_locale.js
- scripts/main/settings.js
- scripts/main/view.js
- styles/main/_header.scss
- styles/main/_settings.scss
Followup to #101, this time on a branch we can all easily push to...
> Public search

- scripts/api.js
- scripts/main/lychee.js
Client side of https://github.com/LycheeOrg/Lychee-Laravel/pull/279, fixing https://github.com/LycheeOrg/Lychee-Laravel/issues/100.
When the server notifies us of session timeout, we let the user know and then reload the top-level albums view.
> Handle timeout

- scripts/main/sidebar.js
- styles/main/_content.scss
- styles/main/_imageview.scss
- styles/main/_justified_layout.scss
> Fix sidebar

- scripts/main/view.js
Inspired by @ildyria's 336a70fa5e8b7cb4f265d41f5964d84161f7cbbf I found another one...
> Fix another issue related to the right padding

- scripts/main/albums.js
- scripts/main/view.js
Front end support for smart albums in publicMode. In practice only Recent will be displayed but I made it generic.
> Support smart albums in publicMode

- scripts/main/album.js
- scripts/main/contextMenu.js
- scripts/main/header.js
- scripts/main/photo.js
- scripts/main/sidebar.js
- scripts/view/main.js
Fixes https://github.com/LycheeOrg/Lychee-Laravel/issues/216.
Support for download via multiselect is v4-only...
Note that since this depends on modifications to the server protocol, the corresponding server changes (https://github.com/LycheeOrg/Lychee-Laravel/pull/296) need to be merged at the same time.
> Add Download to context menus

- scripts/main/lychee.js
- scripts/main/multiselect.js
- scripts/main/view.js
- styles/main/_content.scss
- styles/main/_footer.scss
- styles/main/main.scss
...so that the v4 footer doesn't overlap the bottom of the page.
> Make content area shorter

- scripts/main/build.js
- scripts/main/init.js
- scripts/main/photo.js
- scripts/main/view.js
Front-end match to https://github.com/LycheeOrg/Lychee-Laravel/pull/326.
* Make the UI visible when the document is ready.
* Use the new `has_albums` field from the server.
* Unrelated bug fix: don't generate errors when clicking on photos in search results.
* Unrelated bug fix: don't display a tiny image when reloading photo view.
> Visibility

- scripts/main/init.js
- scripts/main/swipe.js
Fixes #112.
Background stays solid, future enhancement can be to make it dynamically transparent.
> Close lightbox by swiping down the photo (mobile only)

- gulpfile.js
- package.json
- scripts/main/lychee.js
- scripts/main/lychee_locale.js
- scripts/main/settings.js
- scripts/main/sidebar.js
- scripts/main/view.js
- styles/main/_settings.scss
Enhancements:
* GPS locations data (latitude, longitude and altitude) is shown in the info panel
* Visualization of location on a map (OpenStreetMap) in the info panel
* Map can be activated and deactivated using the settings menu
* Map uses the leaflet plugin (https://leafletjs.com)
> First version of displaying coordinates on map

- gulpfile.js
- package.json
- scripts/main/lychee_locale.js
- scripts/main/sidebar.js
- scripts/main/view.js
This PR enhances the map functionality to also visualize the direction of the photo (if Exif image direction data is available).
> Enhance map to visualize the direction of the photo

- scripts/main/album.js
- scripts/main/photo.js
- scripts/main/view.js
Fixes #142.
Assorted minor fixes:
* Next/Prev photo prefetch was misbehaving on Firefox for HiDPI images
* Prefetch was doing more than it should for video files
* An earlier optimization that eliminated unnecessary reloads during image moves didn't handle the case of moving to a new album so it got reverted
* Wrapping of html code with `lychee.html` was added where missing
> Small fixes

- scripts/main/build.js
- scripts/main/header.js
- scripts/main/lychee.js
- scripts/main/lychee_locale.js
- scripts/main/search.js
- scripts/main/sidebar.js
- styles/main/_sidebar.scss
**1. Search**
* Change URL to format '#search/searchstring' for searches
* set title for result page to 'Search results'
**2. Search by clicking on tags**
* Click on a photo tag triggers the search for this tag (only works if search is available, e.g. not for public if public_search = false)
* tags are always visible, but only editable when photo is editable
> Search by clicking on tags and modify search to change URL

- scripts/frame/main.js
While fixing https://github.com/LycheeOrg/Lychee-Laravel/issues/390 I noticed that the refresh of the image would often flicker, with new image being rendered too late. I'm not sure if I fixed it 100% but I sure made it better...
I also cleaned up the code a bit in the process, including fixing the case when full-size images are disabled.
> Frame refresh

- scripts/main/album.js
- scripts/main/photo.js
- scripts/view/main.js
Update facebook share URL from http to https.
> update facebook share url http to https

- LICENSE
- scripts/main/header.js
fixes icon not showing when album is downloadable without pictures but subalbums
> fix small bug on header.

- .travis.yml
Now that the dependencies should be fixed.
> Put travis node version back to automatic

- scripts/main/build.js
Corresponding PR for Lychee/#564
Lightbox shows medium size jpg for raw files, if available
> Show medium size file of raw file in lightbox

- scripts/main/photo.js
to hide live photo on download modal when not present
> hide live photo download

- scripts/main/view.js
- styles/main/_justified_layout.scss
Doesn't change the default, simply makes it configurable via user.css.
> Make photo height configurable via CSS

- scripts/main/album.js
- scripts/main/photo.js
Fixes https://github.com/LycheeOrg/Lychee/issues/723
> Match the title limits of the server

- scripts/main/album.js
- scripts/main/lychee_locale.js
- scripts/main/sidebar.js
In relation with https://github.com/LycheeOrg/Lychee/pull/758
> add ordering per album

- README.md
The CI badge is still linked to TravisCI.
#234
> update CI status badge

- scripts/main/lychee_locale.js
- scripts/main/upload.js
Frontend part of https://github.com/LycheeOrg/Lychee/pull/865.
> Improve diagnostics when PHP limits are exceeded

- scripts/main/album.js
- scripts/main/header.js
- scripts/main/lychee_locale.js
- scripts/main/view.js
- styles/main/_message.scss
- styles/main/_sharing.scss
This PR adds a new icon in the top bar, next to the album visibility option.
On click, it opens a modal with the list of users, asking to choose which one to share it with.
See LycheeOrg/Lychee#885 for the related code in the front
> Allow to share an album with users right from the album page

- scripts/main/header.js
Fixes https://github.com/LycheeOrg/Lychee/issues/917
> Handle back button from albums view map correctly

- deps/basiccontext/scripts/basicContext.js
- deps/basiccontext/styles/_context.scss
Fixes https://github.com/LycheeOrg/Lychee/issues/934
> Account for window scrollbars

- scripts/main/album.js
- scripts/main/albums.js
- scripts/main/build.js
- scripts/main/lychee_locale.js
- scripts/main/mapview.js
- scripts/main/photo.js
- scripts/main/sidebar.js
- scripts/main/view.js
This PR is related to [PR #1016](https://github.com/LycheeOrg/Lychee/pull/1016) for repository [Lychee](https://github.com/LycheeOrg/Lychee).
The frontend consumes iSO 8601 datetime strings (aka "JSON timestrings") from the REST API incl. correct timezone offsets and converts them to a localized string at the GUI layer for all datetime attribues.
> Refactor timestamps

- scripts/main/leftMenu.js
- scripts/main/lychee.js
- scripts/main/lychee_locale.js
- scripts/main/notifications.js
- scripts/main/settings.js
- scripts/main/view.js
This is for the PR on the Backend #1049. Notes are on that PR
> New Photos Email Notification

- README.md
> Possible fix for: `no issue have been opened for this`
This PR aims to update the `README.md` file, removing the out-of-date Live Demo link, that leads to nothing.
None.
> Removed out-of-date Live Demo link from README

- scripts/main/contextMenu.js
Fixes https://github.com/LycheeOrg/Lychee/issues/1204
I thought I eliminated all instances of `photo.json.album` in one of my earlier commits but I guess somehow this one got left over...
> Fix the leftover instance of photo.json.album

- styles/main/_header.scss
Frontend part of https://github.com/LycheeOrg/Lychee/pull/1264
> Center clear search `X`

- scripts/main/album.js
- scripts/main/photo.js
A small tweak to #287 to eliminate the hardcoded size.
> Eliminate the hardcoded size

- scripts/3rd-party/backend.js
- scripts/main/album.js
- scripts/main/contextMenu.js
- scripts/main/header.js
- scripts/main/lychee.js
- scripts/main/multiselect.js
- scripts/main/settings.js
- scripts/main/view.js
This are the front-end changes for https://github.com/LycheeOrg/Lychee/pull/1443.
> Add user and better structure to session json

- scripts/main/album.js
- scripts/main/users.js
- scripts/main/view.js
Some bugs I found for #320  while working on https://github.com/LycheeOrg/Lychee/pull/1601
What should happen with the `is_share_button_visible` statements?
> Some fixes for naming rights

- scripts/main/lychee.js
> Fix URLs in RSS feeds (Lychee-front#1732)

- scripts/main/lychee.js
Fixes https://github.com/LycheeOrg/Lychee/issues/1794
Fixes https://github.com/LycheeOrg/Lychee/issues/1780
Fixes https://github.com/LycheeOrg/Lychee/issues/1765
> Fix mapping - Configs are sent in the correct type.

- scripts/main/settings.js
Fixes https://github.com/LycheeOrg/Lychee/issues/1778
> Fix API token dialog box

- scripts/main/lychee_locale.js
- scripts/main/view.js
Associated pull request for https://github.com/LycheeOrg/Lychee/pull/1848
> Remove option public for album sorting

- scripts/main/lychee.js
Make behavior consistent with PHP backend logic, fixes https://github.com/LycheeOrg/Lychee/issues/1834
> fix: Dont escape html for footer

- scripts/main/album.js
- scripts/main/photo.js
- scripts/main/settings.js
basicModal doesn't bring a label on the callback that is why it shows undefined. However we don't need to set the label value on the callback as the label doesn't need to be dynamic. So we can just set the translated value inside setPhotoLicenseDialogBody
> fix: #1853 from Lychee.
